[packages]
recipe = { path = "recipe"}
auth = { path = "authentication" }
frontend = { path = "web-service" }
orchestration = { path = "orchestration" }
reverseproxy = { path = "reverse-proxy" }
loadbalancer = { path = "load-balancer" }
loadtest = { path = "loadtest" }