apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '8080'
spec:
  selector: 
    app: grafana
  type: NodePort  
  ports:
    - port: 8080
      targetPort: 8080