apiVersion: v1
kind: Service
metadata:
  name: authentication
spec:
  selector:
    app: authentication
    tier: backend
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer