apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe
spec:
  selector:
    matchLabels:
      app: hello
      tier: recipe
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: recipe
        track: stable
    spec:
#      volumes:
#        - name: volume-example-pv
#          persistentVolumeClaim:
#            claimName: example-pv
      containers:
        - name: recipe-service
          env:
          - name: JWT_PUBLIC_KEY
            value: "/jwt-pub-key-volume/jwt_public_key.key"
          - name: AUTH_RPC_TARGET
            value: "authentication:3001"
          envFrom:
          - secretRef:
              name: recipe-db-secret
          imagePullPolicy: Always
          image: ghcr.io/stockhut/hsfl-master-ai-cloud-engineering/recipe:0.4.0
          volumeMounts:
            # name must match the volume name below
            - name: jwt-pub-key-volume
              mountPath: /jwt-pub-key-volume
              readOnly: true
          #lifecycle:
            #preStop:
              #exec:
                #command: ["/usr/sbin/nginx","-s","quit"]
#          volumeMounts:
#          - mountPath: "/data"
#            name: volume-example-pv
      volumes:
        - name: jwt-pub-key-volume
          secret:
            secretName: jwt-public-key