name: Auth test and docker

on:
  push:
    paths:
      - 'authentication/**'
      - '.github/workflows/auth-test.yml'
      - '.github/workflows/auth-build-push-image'
      - '.github/workflows/auth-test-and-deliver.yml'
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/auth-test.yml
  docker:
    needs:
      - test
    uses: ./.github/workflows/auth-build-push-image.yml