name: Build and push docker image for authentication

on:
  #workflow_run:
  #  workflows: [Test auth service]
  #  types: [completed]

  workflow_dispatch:
  workflow_call:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # to fetch tags
          ref: versioning-test # TODO remove

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=auth-{{version}}
          images: ghcr.io/${{ github.repository }}/authentication

      - run: git log
      - run: git tag

      - name: Set docker tag from git tag
        id: gittag
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo tag=$( git tag --points-at HEAD | grep auth ) >> "$GITHUB_OUTPUT"

      - run: echo ${{ steps.gittag.outputs.tag }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./authentication/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}, ghcr.io/${{ github.repository }}/authentication:${{ steps.gittag.outputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}
