name: Check

on:
  workflow_call:
    inputs:
      workdir:
        required: true
        type: string

jobs:
  check:
    name: Setup Go 🛠️
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'
          cache-dependency-path: ${{ inputs.workdir }}/go.sum

      - name: Install mockgen
        run: go install go.uber.org/mock/mockgen@latest

      - name: Go generate mocks
        run: go generate _mocks/gen.go