name: Test auth service

on:
  push:
    paths:
      - 'authentication/**'
      - '.github/workflows/test-auth.yml'

  workflow_dispatch:

jobs:
  test:
    name: Test auth service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: authentication

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'
          cache-dependency-path: authentication/go.sum

      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code

      - name: Install mockgen
        run: go install go.uber.org/mock/mockgen@latest

      - name: Install protobuf dependencies
        run: sudo apt install -y protobuf-compiler
      - run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Generate protobuf code
        run: go generate auth-proto/gen.go

      - name: Go generate mocks
        run: go generate _mocks/gen.go

      - name: Go Vet
        run: go vet ./...

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

      - name: Go Mod
        run: go mod download

      - name: Go Mod Verify
        run: go mod verify

      - name: Go Build
        run: go build -o /dev/null ./...

      - name: Go Test
        run: go test -race -shuffle=on -coverprofile=coverage.txt ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        continue-on-error: true
        with:
          flags: auth
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}