name: Test reverse-proxy

on:
  push:
    paths:
      - 'reverse-proxy/**'
      - '.github/workflows/test-reverse-proxy.yml'

  workflow_dispatch:

jobs:
  test:
    name: Test reverse proxy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: reverse-proxy

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'
          cache-dependency-path: reverse-proxy/go.sum

      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code

      - name: Go Vet
        run: go vet ./...

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

      - name: Go Mod
        run: go mod download

      - name: Go Mod Verify
        run: go mod verify

      - name: Go Build
        run: go build -o /dev/null ./...

      - name: Go Test
        run: go test -race -shuffle=on -coverprofile=coverage.txt ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        continue-on-error: true
        with:
          flags: reverseproxy
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
